### ISSUE TITLE
Undefined namespace prefix: .//ds:Modulus

### ISSUE THREAD

**Issue by manoveg** [railslove/epics#22] opened 2015-07-14 12:41 UTC
Hi,

I have generated the INI letter, sent it to the bank and bank has confirmed account is activated.
I am now trying the next step.

giving the correct details in the parameters below
e = Epics::Client.new(File.open('/tmp/my.key'), 'passphrase', 'url', 'host', 'user', 'partner')
e.HPB

but it is failing with following error at e.HPB
Nokogiri::XML::XPath::SyntaxError 
Undefined namespace prefix: .//ds:Modulus

**Comment by kangguru** [comment] 2015-07-14 12:59
glad to hear that the ini now worked.

could you provide the complete backtrace as gist? i suppose it happens here: https://github.com/railslove/epics/blob/962a98a3088fafa42afcf4bab65b60c4d3ef2531/lib/epics/client.rb#L101 correct?

i'd be helpful if you could then also provide the result of `e.send(:download, Epics::HPB)` these are the public parts of the bank keys

**Comment by manoveg** [comment] 2015-07-14 13:49
Yes it seems to fail here only
https://github.com/railslove/epics/blob/962a98a3088fafa42afcf4bab65b60c4d3ef2531/lib/epics/client.rb#L101

link to gist is
https://gist.github.com/manoveg/f5b6f1c373fec169b82b

**Comment by kangguru** [comment] 2015-07-14 14:35
just push a fix to `master` which will address this issue. could you please try if the issue is solved?

**Comment by manoveg** [comment] 2015-07-14 15:22
Thanks . It works now.
I can get the records using puts e.STA('2014-09-01', '2014-09-11')

**Comment by kangguru** [comment] 2015-07-21 07:27
closed via #a0975ec1d2fff52432c3e0144c70e32865c006e8

**Closed by kangguru** 2015-07-21 07:27 UTC
Labels: bug
